name: Main test

# Triggered when pushing/pulling
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Pretty cargo stuff
env:
  CARGO_TERM_COLOR: always

# Jobs
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        format:
          - json5
          - toml
          - yaml
          - json5,toml,yaml
    steps:
    - uses: actions/checkout@v3
    - name: Update toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose --features ${{ matrix.format }}
    - name: Run tests
      run: cargo test --verbose --features ${{ matrix.format }}
